services:
  test:
    image: node:rd-test
    build: .
    environment:
      - RD_MODE=DEV
      - NODE_ENV=production
      - PORT=3000
    ports: 
      - 3000:3000
    command: npm run serve
    volumes:
      - /data/websites/legendapi/envs/keys:/usr/src/app/keys
